trigger:
- no

pool:
  vmImage: windows-latest


steps:
  
- script: |
   echo 'test -Dcucumber.filter.tags="@$(tag)" -Dbrowser=$(browser) -Dplatform=Linux -DRemoteHubExecution=$(remoteHubExecution) -DTestRunner=testRunner.java'

   
- task: Maven@1
  displayName: 'Running cucumber tag $(tag)'
  inputs:
    mavenPomFile: 'automation/pom.xml'
    goals: test
    options: '-Dcucumber.filter.tags="@$(tag)" -Dbrowser=$(browser) -Dplatform=Linux -DRemoteHubExecution=$(remoteHubExecution) -DTestRunner=testRunner.java'
    publishJUnitResults: false
    mavenAuthenticateFeed: false
    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'automation/target/report/**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  
- task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
  displayName: 'Publish Html Report'
  inputs:
    tabName: 'HTML-Report for $(tag)'
    reportDir: '$(build.artifactstagingdirectory)/automation/target/report/report.html'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()