trigger:
- no

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      https://github.com/tiddhacker/Hybrid-Framework-Cucumber-Skeleton.git
      pwd