trigger:
- no

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      https://github.com/tiddhacker/Hybrid-Framework-Cucumber-Skeleton.git
      pwd
      ls
      mvn -f automation/pom.xml clean compile test -Dcucumber.filter.tags="@Regression" -Dbrowser=Chrome -Dplatform=Linux -DRemoteHubExecution=No -DTestRunner=testRunner.java