trigger:
- no

pool:
  vmImage: windows-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      git clone https://github.com/tiddhacker/Hybrid-Framework-Cucumber-Skeleton.git
      dir /s /b /o:gn
      cd
      mvn -f automation/pom.xml clean compile test -Dcucumber.filter.tags="@Regression" -Dbrowser=Chrome -Dplatform=Linux -DRemoteHubExecution=No -DTestRunner=testRunner.java