trigger:
- no

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo - task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean compile test -Dcucumber.filter.tags="@Test" -Dbrowser=Chrome -Dplatform=Linux -DRemoteHubExecution=No -DTestRunner=testRunner.java'
    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Selenium POM Skeleton'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Test run project from GIT'
