trigger:
- no

pool:
  vmImage: ubuntu-latest

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@3
  displayName: Install Maven dependencies
  inputs:
    mavenPomFile: 'automation/pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
- task: CmdLine@2
  displayName: Run groupname tests
  inputs:
    script: mvn clean compile test -Dcucumber.filter.tags="@Registration" -Dbrowser=Chrome -Dplatform=Linux -DRemoteHubExecution=No -DTestRunner=testRunner.java
